name: Lint
on: push
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip &&
          pip install -r requirements-dev.txt
      - name: Lint with ruff
        run: ruff check .
      - name: Lint with flake8
        run: flake8 .
      - name: Type checking
        run: mypy
